apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberay-operator
  namespace: system
  labels:
    app.kubernetes.io/name: kuberay
    app.kubernetes.io/component: kuberay-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kuberay
      app.kubernetes.io/component: kuberay-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kuberay
        app.kubernetes.io/component: kuberay-operator
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kuberay-operator
      containers:
      - command:
        - /manager
#        args:
#        - --enable-leader-election
        image: kuberay/operator
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        name: kuberay-operator
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      terminationGracePeriodSeconds: 10
