
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: kuberay-operator
  name: kuberay-operator-metrics-monitor
  namespace: ray-system
spec:
  endpoints:
    - path: /metrics
      port: monitoring-port
  selector:
    matchLabels:
      control-plane: kuberay-operator
